version: 2.1 # use CircleCI 2.0

orbs:
  jira: circleci/jira@1.0.5
  #slack: circleci/slack@4.1.3

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      #- run: git submodule sync
      #- run: git submodule update --init
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              make openssl tar gzip curl
      #        py-pip=9.0.0-r1
      #      pip install \
      #        docker-compose==1.12.0 \
      #        awscli==1.11.76
      #- restore_cache:
      #    keys:
      #      - v1-{{ .Branch }}
      #    paths:
      #      - /caches/builder.tar
      #- run:
      #    name: Load Docker image layer cache
      #    command: |
      #      set +o pipefail
      #      docker load -i /caches/builder.tar | true
      - run:
          name: Build application Docker image
          command: |
            #docker build \
            #  --cache-from=lfs-builder \
            #  -t innovanon/lfs-builder \
            #  --build-arg TEST=1 .
            make TEST='--build-arg TEST=1'
      #- run:
      #    name: Save Docker image layer cache
      #    command: |
      #      mkdir -p /caches
      #      docker save -o /caches/builder.tar builder
      #- save_cache:
      #    key: v1-{{ .Branch }}-{{ epoch }}
      #    paths:
      #      - /caches/builder.tar
      #- run:
      #    name: Run tests
      #    command: |
      #      docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              #docker tag lfs-builder "InnovAnon-Inc/lfs-builder:${CIRCLE_SHA1}"
              #docker push           "InnovAnon-Inc/lfs-builder:${CIRCLE_SHA1}"
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              docker push innovanon/signer
            fi
#      - run:
#          name: Push upstream (pusher)
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              curl --location --request POST \
#                'https://circleci.com/api/v2/project/github/InnovAnon-Inc/pusher/pipeline' \
#                --header 'Content-Type: application/json' \
#                -u "${PUSHER_API_TOKEN}:"
#            fi
#
#
